### ISSUE TITLE
simple_frozen_graph

### ISSUE THREAD

**Issue by Nexact** [Obserbant/NewWorldMusic#1]
Hello! 

Curiously, how do you generate the frozen graph ? 

Thanks!

**Comment by Obserbant** [comment]
I mainly followed https://ksingh7.medium.com/part-iii-convert-keras-model-to-tensorflow-frozen-graph-model-a6aa6b1aaeee
I have added the file I used as well as a test with an example how to to get a result from the frozen model.

**Comment by Nexact** [comment]
Thank you. That's a nice exercise. I'll need to read a bit so I can generate my own .pb. Did you build the model from scratch ?

**Comment by Obserbant** [comment]
No, I forget what tutorial I used, but it's based on VGG19. Looking over it, there were pre-trained layers which I didn't touch. I added the file I used to train it if you want to take a look.

**Comment by Nexact** [comment]
So, I've put all the piece together and made my frozen model and I've went from 0 to 164 music over night. Getting from 2 start to 3 stars performance. I'm not sure if it's caused by the input latency or something else. Have you figured it out ?

**Comment by Obserbant** [comment]
It's so much faster to level music now, but I'm still wary of leaving it running for more than a few hours at a time. I was never able to get perfect with it. There were several issues I identified but didn't feel the need to fix:
1. It identifies and presses the same note more than once, ruining the following note.
2. I didn't come up with a specific rule set when creating my data set, so it handles multiple notes showing up at once in unspecified ways.
3. I believe the background of where I trained it at not matching the current play location negatively affected it's performance.
4. I can't reliably get perfect even when I do it myself; I didn't even bother trying to establish the precise time windows for note playing required, and instead settled for 3 star performances as that matched the stated goal of the project.

If you can get a version working with reliably better performance please let me know.
